name: Python Package CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Action to check out your repository code

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python
      with:
        python-version: '3.9' # Specify the Python version you want to use (e.g., 3.8, 3.9, 3.10)

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel # Install tools needed to build the package

    - name: Build Python package
      run: |
        python setup.py sdist bdist_wheel # Build source distribution and wheel package

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4 # Action to upload built files as artifacts
      with:
        name: python-package-build
        path: dist/ # The 'dist' directory contains the built .tar.gz and .whl files

    - name: Display built artifacts (Optional)
      run: |
        echo "Built artifacts in dist/:"
        ls -l dist/
